// Auth
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const SET_ERROR = "SET_ERROR";

// Messages
const SET_MESSAGE = "SET_MESSAGE";

// Users
const GET_USER = "GET_USER";
const GET_ALL_USERS = "GET_ALL_USERS";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";

// Events
const CREATE_EVENT = "CREATE_EVENT";
const GET_ALL_EVENTS = "GET_ALL_EVENTS";
const GET_EVENT = "GET_EVENT";
const UPDATE_EVENT = "UPDATE_EVENT";
const DELETE_EVENT = "DELETE_EVENT";
const GET_THREE_FIRST_EVENTS = "GET_THREE_FIRST_EVENTS";

//  Actus
const GET_ALL_ACTUS = "GET_ALL_ACTUS";
const GET_ACTU = "GET_ACTU";
const GET_ACTU_BY_ID = "GET_ACTU_BY_ID";
const UPDATE_ACTU = "UPDATE_ACTU";
const DELETE_ACTU = "DELETE_ACTU";
const CREATE_ACTU = "CREATE_ACTU";

//  Paroisse
const CREATE_PAROISSE = "CREATE_PAROISSE";
const GET_ALL_PAROISSE = "GET_ALL_PAROISSE";
const GET_NEAR_PAROISSES = "GET_NEAR_PAROISSES";
const GET_PAROISSE = "GET_PAROISSE";
const UPDATE_PAROISSE = "UPDATE_PAROISSE";
const DELETE_PAROISSE = "DELETE_PAROISSE";
const CHOOSE_PAROISSE = "CHOOSE_PAROISSE";
const UNCHOOSE_PAROISSE = "UNCHOOSE_PAROISSE";
const ADD_PRIEST = "ADD_PRIEST";
const REMOVE_PRIEST = "REMOVE_PRIEST";
const ADD_MESSE = "ADD_MESSE";
const REMOVE_MESSE = "REMOVE_MESSE";
const REMOVE_CONFESSION = "REMOVE_CONFESSION";

export {
  AUTH,
  LOGOUT,
  SET_ERROR,
  SET_MESSAGE,
  GET_USER,
  GET_ALL_USERS,
  UPDATE_USER,
  DELETE_USER,
  CREATE_EVENT,
  GET_ALL_EVENTS,
  GET_THREE_FIRST_EVENTS,
  GET_EVENT,
  UPDATE_EVENT,
  DELETE_EVENT,
  GET_ALL_ACTUS,
  GET_ACTU,
  GET_ACTU_BY_ID,
  UPDATE_ACTU,
  DELETE_ACTU,
  CREATE_ACTU,
  CREATE_PAROISSE,
  GET_ALL_PAROISSE,
  GET_PAROISSE,
  UPDATE_PAROISSE,
  DELETE_PAROISSE,
  CHOOSE_PAROISSE,
  UNCHOOSE_PAROISSE,
  GET_NEAR_PAROISSES,
  ADD_PRIEST,
  REMOVE_PRIEST,
  ADD_MESSE,
  REMOVE_MESSE,
  REMOVE_CONFESSION,
};
